FROM node:8

ARG WORKDIR
ARG SERVER_PORT
ARG BTC_PORT
ARG ETH_PORT
ARG LTC_PORT
ARG NETS_LOCATION
ARG STREAMS_LOCATION

ENV SERVER_PORT $SERVER_PORT
ENV BTC_PORT $BTC_PORT
ENV ETH_PORT $ETH_PORT
ENV LTC_PORT $LTC_PORT
ENV WORKDIR $WORKDIR
ENV NETS_LOCATION $NETS_LOCATION
ENV STREAMS_LOCATION $STREAMS_LOCATION

WORKDIR /$WORKDIR

COPY package.json ./
COPY yarn.lock ./
RUN yarn

COPY . ./

EXPOSE $SERVER_PORT $BTC_PORT $ETH_PORT $LTC_PORT
CMD ["sh", "-c", "yarn bitcoin"]
